#  _____              __ _          __ _ _      
# /  __ \            / _(_)        / _(_) |     
# | /  \/ ___  _ __ | |_ _  __ _  | |_ _| | ___ 
# | |    / _ \| '_ \|  _| |/ _` | |  _| | |/ _ \
# | \__/\ (_) | | | | | | | (_| | | | | | |  __/
#  \____/\___/|_| |_|_| |_|\__, | |_| |_|_|\___|
#                           __/ |               
#                          |___/                
crt: keys/server.crt
key: keys/server.key
port: 8080
storage: data
user: admin
password: 1234